### ISSUE TITLE
Do a release

### ISSUE THREAD

**Issue by fivethreeo** [jantimon/webpack-recompilation-simulator#4]
Do a release, github packages won’t do public packages so we are stuck at doing scoped npm packages. Can you do a alpha of this package?
Webpack 5 is a moving target so my solution and a full release is a bit premature. I added some github actions in my webpack5-act branch that can automate the testing and releases if it is of interest. If you add me as a collaborator I could take care of the release and matrix tests if you add a npm token to the repo. Anyway, just a offer 😀

**Comment by jantimon** [comment]
Done 👍

`webpack-recompilation-simulator@3.2.0` is out thank you so much for your efforts :)
